## Importar librerias necesarias

In [18]:
from ydata_profiling import ProfileReport
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
plt.style.use("seaborn-v0_8")

## Cargar archivos CSV

In [19]:
# Cargar datos del 2015
df2015 = pd.read_csv("../../datos/crudos/2015.csv", 
                   encoding="latin-1", low_memory=False)

print(f"Fuente 2015: {df2015.shape[0]} rows, {df2015.shape[1]} columns")

Fuente 2015: 158 rows, 12 columns

In [9]:
df2015.head(2)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201

In [20]:
# Cargar datos del 2016
df2016 = pd.read_csv("../../datos/crudos/2016.csv", 
                   encoding="latin-1", low_memory=False)

print(f"Fuente 2016 (Santander): {df2016.shape[0]} rows, {df2016.shape[1]} columns")

Fuente 2016 (Santander): 157 rows, 13 columns

In [10]:
df2016.head(2)

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463

In [21]:
# Cargar datos del 2017
df2017 = pd.read_csv("../../datos/crudos/2017.csv", 
                   encoding="latin-1", low_memory=False)

print(f"Fuente 2017: {df2017.shape[0]} rows, {df2017.shape[1]} columns")

Fuente 2017: 155 rows, 12 columns

In [11]:
df2017.head(2)

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707

In [22]:
# Cargar datos del 2018
df2018 = pd.read_csv("../../datos/crudos/2018.csv", 
                   encoding="latin-1", low_memory=False)

print(f"Fuente 2018: {df2018.shape[0]} rows, {df2018.shape[1]} columns")

Fuente 2018: 156 rows, 9 columns

In [12]:
df2018.head(2)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340

In [23]:
# Cargar datos del 2019
df2019 = pd.read_csv("../../datos/crudos/2019.csv", 
                   encoding="latin-1", low_memory=False)

print(f"Fuente 2019: {df2019.shape[0]} rows, {df2019.shape[1]} columns")

Fuente 2019: 156 rows, 9 columns

In [13]:
df2019.head(2)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410

## EDA con ydata_profiling

In [12]:
#Reporte de fuente 2015
profile1 = ProfileReport(df2015, title="Fuente 2015 - hapiness scores", explorative=True)
profile1.to_file("reporte_2015.html")

100%|██████████| 12/12 [00:00<?, ?it/s]17 [00:00<00:00, 85.20it/s, Describe variable: Dystopia Residual]
Summarize dataset: 100%|██████████| 121/121 [00:05<00:00, 22.93it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.89s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.37it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 82.97it/s]

In [13]:
#Reporte de fuente 2016
profile2 = ProfileReport(df2016, title="Fuente 2016 - hapiness scores", explorative=True)
profile2.to_file("reporte_2016.html")

100%|██████████| 13/13 [00:00<?, ?it/s]18 [00:00<00:00, 103.10it/s, Describe variable: Dystopia Residual]
Summarize dataset: 100%|██████████| 143/143 [00:05<00:00, 23.94it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.14it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 83.33it/s]

In [14]:
#Reporte de fuente 2017
profile3 = ProfileReport(df2017, title="Fuente 2017 - hapiness scores", explorative=True)
profile3.to_file("reporte_2017.html")

100%|██████████| 12/12 [00:00<00:00, 11980.87it/s]:00, 123.29it/s, Describe variable: Dystopia.Residual]
Summarize dataset: 100%|██████████| 142/142 [00:06<00:00, 23.38it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.70it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 66.68it/s]

In [15]:
#Reporte de fuente 2018
profile4 = ProfileReport(df2018, title="Fuente 2018 - hapiness scores", explorative=True)
profile4.to_file("reporte_2018.html")

100%|██████████| 9/9 [00:00<00:00, 8989.93it/s]<00:00, 87.50it/s, Describe variable: Perceptions of corruption]
Summarize dataset: 100%|██████████| 82/82 [00:03<00:00, 23.94it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  7.41it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 136.27it/s]

In [16]:
#Reporte de fuente 2019
profile5 = ProfileReport(df2019, title="Fuente 2019 - hapiness scores", explorative=True)
profile5.to_file("reporte_2019.html")

100%|██████████| 9/9 [00:00<00:00, 3000.22it/s]<00:00, 40.00it/s, Describe variable: Perceptions of corruption]
Summarize dataset: 100%|██████████| 82/82 [00:03<00:00, 22.84it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.55s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  8.32it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 125.02it/s]